version: 2.1

jobs:
  test:
    docker:
      - image: racket/racket:7.8
    steps:
      - checkout
      - run:
          name: "Running test suite"
          command: raco test test.rkt

workflows:
  version: 2.1
  test:
    jobs:
      - test



